### ISSUE TITLE
Unable to donate to canoe

### ISSUE THREAD

**Issue by ppeach** [getcanoe/canoe#290] opened 2018-07-05 00:41 UTC
The receive address only shows @[object Object]

**Comment by stefonarch** [comment] 2018-07-05 04:49
Duplicate of https://github.com/getcanoe/canoe/issues/283, it is already fixed in the next release. If I remember well it happens only doing it from "settings", not from the adressbook.

**Closed by stefonarch** 2018-07-05 04:49 UTC
